// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnFzstdtmrdhz9dHZto8YxhHsBiMc-nmo',
    appId: '1:759627269415:web:677be408feab089e3b1502',
    messagingSenderId: '759627269415',
    projectId: 'social-media-202501200108',
    authDomain: 'social-media-202501200108.firebaseapp.com',
    storageBucket: 'social-media-202501200108.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd3q608k9Jv19gdNNpjid0YV5sRtHuSeo',
    appId: '1:759627269415:android:d96b9ae2f97658ff3b1502',
    messagingSenderId: '759627269415',
    projectId: 'social-media-202501200108',
    storageBucket: 'social-media-202501200108.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbEKrjOo-cQDjj3oVTWYGS9283O71drYA',
    appId: '1:759627269415:ios:edfb642cb706fc523b1502',
    messagingSenderId: '759627269415',
    projectId: 'social-media-202501200108',
    storageBucket: 'social-media-202501200108.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbEKrjOo-cQDjj3oVTWYGS9283O71drYA',
    appId: '1:759627269415:ios:edfb642cb706fc523b1502',
    messagingSenderId: '759627269415',
    projectId: 'social-media-202501200108',
    storageBucket: 'social-media-202501200108.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnFzstdtmrdhz9dHZto8YxhHsBiMc-nmo',
    appId: '1:759627269415:web:88b64941dbb5585b3b1502',
    messagingSenderId: '759627269415',
    projectId: 'social-media-202501200108',
    authDomain: 'social-media-202501200108.firebaseapp.com',
    storageBucket: 'social-media-202501200108.firebasestorage.app',
  );

}